version: 0.2

phases:

  install:
    commands:

      - echo "Installing Required Packages"

      - apt-get update

      - apt-get install -y wget unzip

      # Install Trivy
      - TRIVY_VERSION=0.70.0

      - wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

  pre_build:
    commands:

      - echo "Logging into Amazon ECR"

      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 159827196218.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:

      - echo "Building Docker Image"

      - docker build -t frontend ./backend

      - docker tag frontend:latest 159827196218.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - echo "Running Trivy Scan"

      - trivy image frontend:latest

  post_build:
    commands:

      - echo "Pushing Docker Image"

      - docker push 159827196218.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
